# Generated by Django 5.1.2 on 2024-11-28 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay_signal_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_currency', models.CharField(max_length=3)),
                ('target_currency', models.CharField(max_length=3)),
                ('rate', models.DecimalField(decimal_places=6, max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.CharField(default='80adac58a8f2427abf51', max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
