# Generated by Django 5.1.2 on 2024-11-20 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pay_signal_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
